### ISSUE TITLE
`Touched` does not change in devtool

### ISSUE THREAD

**Issue by jsun969** [jsun969/react-hook-form-antd#2]
Reproduce in [example](https://codesandbox.io/s/react-hook-form-antd-example-6s0i3z?file=/src/App.tsx)

![image](https://user-images.githubusercontent.com/29330847/230756060-e441705a-ac99-445e-bdeb-224a743cb4ee.png)

https://github.com/jsun969/react-hook-form-antd/blob/0dc2a63e41d251298828d23575189c02a63b5a4d/src/FormItem.tsx#L15

**Comment by jsun969** [comment]
Need `onBlur`

**Comment by HiChen404** [comment]
reset 也无法正常工作

**Comment by jsun969** [comment]
resolved by #5
