### ISSUE TITLE
The onChange of the antd inputs does not work inside the FormItem

### ISSUE THREAD

**Issue by avegatolber** [jsun969/react-hook-form-antd#73]
[Codesandbox here](https://codesandbox.io/p/sandbox/react-hook-form-antd-example-forked-d4hgn8?file=%2Fsrc%2FApp.tsx&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqid8f1v0006356iv0x0eq0c%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqid8f1u0002356i3ry4l0n4%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqid8f1u0003356ipe4cu9g1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqid8f1u0005356iq00b39oi%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B56.0547997700709%252C43.9452002299291%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqid8f1u0002356i3ry4l0n4%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqid8f1u0001356itdd3clgr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpublic%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clqihy2zl00y5356iu6r2qu1w%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clqid8f1u0002356i3ry4l0n4%2522%252C%2522activeTabId%2522%253A%2522clqihy2zl00y5356iu6r2qu1w%2522%257D%252C%2522clqid8f1u0005356iq00b39oi%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqid8f1u0004356i0wx52760%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqid8f1u0005356iq00b39oi%2522%252C%2522activeTabId%2522%253A%2522clqid8f1u0004356i0wx52760%2522%257D%252C%2522clqid8f1u0003356ipe4cu9g1%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqid8f1u0003356ipe4cu9g1%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A22.8125%257D)

**Comment by jsun969** [comment]
I assume you should try `watch` in react hook form instead of `onChange`. [Docs here](https://react-hook-form.com/docs/useform/watch)

**Comment by avegatolber** [comment]
It seems that the `useController` `field` is overwriting the `onChange` of input

**Comment by jsun969** [comment]
Yea. Also it's not recommended to use `onChange` or `value` with react-hook-form. Check the react hook form's documentation first then use this lib plz.

**Comment by avegatolber** [comment]
I understand but sometimes it is necessary, especially in ANTD Select components, where in the second parameter of the onChange you receive the option with all the information of the selected element, including the id and the label, that is exactly why I need to use the onChange but it is not working.

And the "onChange" through the watch does not give me this information.

I will see what alternative I can find, thanks anyway

**Comment by avegatolber** [comment]
Adding this code to `FormItem` children solved my problem. It's probably not the best way to do it, but it works for me. 
Now i can access to the options from the `onChange` event in the Antd Select component and the form still working as expected.

```typescript
{Children.map(
   children,
      (child) =>
         isValidElement(child) &&
         cloneElement(child, {
           ...field,
           //@ts-expect-error onChange type safe is not necessary here
           onChange: (...params) => {
              child.props.onChange &&
              child.props.onChange(...params)

              field.onChange(...params)
             },
            onBlur: () => {
              child.props.onBlur && child.props.onBlur()
              field.onBlur()
            },
            ...(valuePropName && {
            [valuePropName]: field.value,
       }),
   }),
)}
```

**Comment by jsun969** [comment]
Sounds reasonable. Could you help create a PR for your awesome idea? Thank you so much!

**Comment by avegatolber** [comment]
[PR](https://github.com/jsun969/react-hook-form-antd/pull/74)

Is my first time contributing, I hope I did the PR well 😄.

**Comment by jsun969** [comment]
@avegatolber thx a lot for the PR. There are some minor fixes I need to deal with. I'll publish your feature ASAP!
