### ISSUE TITLE
Error when using Upload component of antd within FormItem

### ISSUE THREAD

**Issue by yorman2401** [jsun969/react-hook-form-antd#83]
When using the **Upload** component of antd as children of a **FormItem** and adding the `valuePropName="fileList"` attribute to the **FormItem**, an error occurs after selecting an image. The error is the following:

![image](https://github.com/jsun969/react-hook-form-antd/assets/66335054/5043e102-9a77-434a-b1f6-ea93a761f359)

and, if for example, I don't add the `valuePropName="fileList"` attribute, I get the following error in the console:

![image](https://github.com/jsun969/react-hook-form-antd/assets/66335054/78d822a6-b514-4809-be22-235ba61bc1f8)

It is important to say that the code works if I do not add the `valuePropName="fileList"` attribute, but I would always have the error in the console.

**Example of my code:**
```ts
"use client";

import { SubmitHandler, useForm } from "react-hook-form";
import { Button, Form, Upload } from "antd";
import { UploadChangeParam } from "antd/lib/upload";
import { FormItem } from "react-hook-form-antd";
import { zodResolver } from "@hookform/resolvers/zod";
import * as z from "zod";

const extensions = ["jpg", "jpeg", "png"];

const schema = z.object({
  image: z
    .custom<UploadChangeParam>()
    .refine(({ file: { name: fileName } }) =>
      extensions.some((ext) => fileName.includes(ext))
    )
    .optional(),
});

type TSchema = z.infer<typeof schema>;

export default function MyFormPage() {
  const { control, handleSubmit } = useForm<TSchema>({
    resolver: zodResolver(schema),
  });

  const onSubmit: SubmitHandler<TSchema> = (data) => {
    console.log(data);
  };

  const normFile = (e: any) => {
    if (Array.isArray(e)) {
      return e;
    }
    return e?.fileList;
  };

  return (
    <Form onFinish={handleSubmit(onSubmit)}>
      <FormItem
        control={control}
        name="image"
        valuePropName="fileList"
        getValueFromEvent={normFile}
        label="Image"
      >
        <Upload listType="picture-card">
          + Upload
        </Upload>
      </FormItem>

     {/* Other fields */}

      <Button type="primary" htmlType="submit">
        Submit
      </Button>
    </Form>
  );
}
```

Also, I think the `getValueFromEvent={normFile}` attribute does nothing.

**Environment:**
- Next.js version: 14.1.0
- Antd version: 5.14.2
- react-hook-form-antd version: 1.1.0
- react-hook-form version: 7.50.1
- hookform/resolvers version: 3.3.4
- Zod version: 3.22.4
- Browser: Chrome

I appreciate any guidance or solutions to address this issue. Thanks for your help!

**Comment by kkfive** [comment]
mark

**Comment by jsun969** [comment]
> what's the update on this ?

Sry kinda busy lately. PRs welcome for this issue. I'll review ASAP.
