### ISSUE TITLE
TypeError: elm.focus is not a function

### ISSUE THREAD

**Issue by snndmnsz** [jsun969/react-hook-form-antd#97]
I get this error when i put Upload component inside FormItem. Probably <Control/> cannot find the focus bcs of Upload uses button. How can i resolve this?

<img width="576" alt="Ekran Resmi 2024-08-09 02 26 21" src="https://github.com/user-attachments/assets/88e859a6-ef62-454f-a6cf-710332416b6b">

Error source:
<img width="638" alt="Ekran Resmi 2024-08-09 02 30 10" src="https://github.com/user-attachments/assets/642766ba-3e0f-40b1-b614-82b1ccfb8cf1">

**Comment by jsun969** [comment]
Have you tried to use the solution in #83 ?

**Comment by snndmnsz** [comment]
@jsun969   Yes, I did, but it didn't work. I found the solution, tho. React Hook Form tries to focus on the error state. Since upload components have no focusable elements, it throws an "**elm.focus is not a function**" error. If you set **`shouldFocusError: false`** in your useForm, it fixes the problem, but you can't use the focus-on-error functionality anymore. Could you please add this problem to the .md file of this package so that everyone who wants to use uploads in their form can resolve this issue?

**Comment by jsun969** [comment]
Yea we should add it in readme. Do you want to make a PR for it?

**Comment by snndmnsz** [comment]
Yeah, sure.
